version: "3.5"
  
services:
  traefik:
    image: "traefik:${TRAEFIK_TAG}"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - matrix-proxy-net
      - nextcloud-proxy-net
      - invoice-old-proxy-net
      - invoice-proxy-net
      - jfc-invoice-proxy-net
      - monitoring-proxy-net
      - noops-proxy-net
      - fotobox-proxy-net
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
      - 8080
    volumes:
      - "./volumes/traefik/letsencrypt:/letsencrypt"
      - "./volumes/traefik/logs:/logs"
      - "./volumes/traefik/etc/traefik.yml:/traefik.yml"
      - "./volumes/traefik/etc/traefik-dynamic.yml:/traefik-dynamic.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  matrix-proxy-net:
    name: matrix-proxy-net
  nextcloud-proxy-net:
    name: nextcloud-proxy-net
  invoice-proxy-net:
    name: invoice-proxy-net
  invoice-old-proxy-net:
    name: invoice-old-proxy-net
  jfc-invoice-proxy-net:
    name: jfc-invoice-proxy-net
  monitoring-proxy-net:
    name: monitoring-proxy-net
  noops-proxy-net:
    name: noops-proxy-net
  fotobox-proxy-net:
    name: fotobox-proxy-net

